name: celebside
description: celebSide

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_switch: ^0.3.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  sliding_up_panel: ^2.0.0+1
  flutter_rating_bar: ^4.0.0
  font_awesome_flutter: ^9.1.0
  url_launcher: ^6.0.9
  dropdown_search:
  flutter_datetime_picker: ^1.5.1
  country_code_picker: ^2.0.2
  duration_picker_dialog_box: ^1.0.1
  syncfusion_flutter_calendar: ^19.2.57
  firebase_core: "^1.5.0"
  cloud_firestore: ^2.5.1
  firebase_auth: ^3.1.0
  localstorage:
  multiselect_dropdown: ^2.0.0+1
  firebase_storage: ^10.0.3
  image_picker: ^0.8.4
  flutter_inappwebview: ^5.3.2
  google_sign_in: "^4.5.1"
  multi_sort: ^3.0.0
  cloud_functions:
  http:
  whatsapp_share: ^1.1.1
  auto_size_text: ^2.1.0
  clipboard_manager:
  location: ^4.2.0
  camera:
  path: ^1.8.0
  path_provider:
  chewie:
  video_player: ^2.2.3  #  video_player: ^2.2.6
  google_maps_flutter: ^2.0.9 #  google_maps_flutter: ^2.0.11
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.2
  video_thumbnail: ^0.4.3
  firebase_dynamic_links: ^2.0.6
  image_gallery_saver: ^1.7.1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/welcome/
    - assets/videoPlayer/
    - assets/forgotPassword/
    - assets/
    - assets/requests/
    - assets/profile/
    - assets/fanPage/
    - assets/login/
    - assets/featured/
    - assets/search/
    - assets/featuredVideoPlayer/
    - assets/signupOptions/
    - assets/createAccount/
    - assets/celebProfile/
    - assets/chatscreen/
    - assets/notificationpermission/
    - assets/bottom bar/glow/
    - assets/bottom bar/simple/
    - assets/requestVideo/
    - assets/howRefundWorks/
    - assets/paymentSuccessful/
    - assets/celebrityWelcome/
    - assets/requestCard/
    - assets/createPass/

  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/helvetica.ttf
    - family: Avenir
      fonts:
        - asset: fonts/avenir.otf
    - family: AvenirBold
      fonts:
        - asset: fonts/avenirBold.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
